apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: k9-los-oidc-auth-proxy
    namespace: default
    labels:
        team: k9saksbehandling
spec:
    image: ghcr.io/navikt/oidc-auth-proxy:2021.04.13-2b87c94
    port: 8080
    liveness:
        path: isalive
        initialDelay: 20
        periodSeconds: 5
        timeout: 1
        failureThreshold: 10
    readiness:
        path: isready
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://k9-los-oidc-auth-proxy.dev.adeo.no
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: false
        path: /metrics
    vault:
      enabled: true
      paths:
        - mountPath: /var/run/secrets/nais.io/vault
          kvPath: /kv/preprod/fss/k9-los-oidc-auth-proxy/default
        - mountPath: /var/run/secrets/nais.io/azuread
          kvPath: /azuread/data/dev/creds/k9-los-oidc-auth-proxy
    webproxy: true
    env:
        - name: CLIENT_ID
          value: a084abb8-6a38-4506-84c2-e4ac8b438a05
        - name: DISCOVERY_URL
          value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
        - name: LOGIN_SCOPES
          value: 'openid profile a084abb8-6a38-4506-84c2-e4ac8b438a05/.default'
        - name: OIDC_AUTH_PROXY_BASE_URL
          value: https://k9-los-oidc-auth-proxy.dev.adeo.no
        - name: APPLICATION_BASE_URL
          value: https://k9-los-web.dev.adeo.no
        - name: ALLOW_PROXY_TO_SELF_SIGNED_CERTIFICATES
          value: 'true'
        - name: SESSION_ID_COOKIE_NAME
          value: k9-los-web
        - name: PROXY_CONFIG
          value: '{"apis":[{"path":"k9-los-api","url":"https://k9-los-api.dev.adeo.no/api","scopes":"5afad323-c9df-4e14-b481-b278e9d2bf69/.default","enableWebSocket":true}]}'
        - name: REDIS_HOST
          value: k9-los-oidc-auth-proxy-redis.default.svc.nais.local
        - name: REDIS_PORT
          value: '6379'
        - name: CORS_ALLOWED_HEADERS
          value: 'Content-Type,Referer,X-Nav-NorskIdent,cache-control,expires,nav-callid,pragma'
        - name: CORS_EXPOSED_HEADERS
          value: 'Location'

