apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: k9-los-oidc-auth-proxy
    namespace: default
    labels:
        team: k9saksbehandling
spec:
    image: ghcr.io/navikt/oidc-auth-proxy:2021.04.13-4e00a7a
    port: 8080
    liveness:
        path: isalive
        initialDelay: 20
        periodSeconds: 5
        timeout: 1
        failureThreshold: 10
    readiness:
        path: isready
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://k9-los-oidc-auth-proxy.nais.adeo.no
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: false
        path: /metrics
    vault:
      enabled: true
      paths:
        - mountPath: /var/run/secrets/nais.io/vault
          kvPath: /kv/prod/fss/k9-los-oidc-auth-proxy/default
        - mountPath: /var/run/secrets/nais.io/azuread
          kvPath: /azuread/data/prod/creds/k9-los-oidc-auth-proxy
    webproxy: true
    env:
        - name: CLIENT_ID
          value: 0dc85ed5-a4d7-4893-8424-700ee6725067
        - name: DISCOVERY_URL
          value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
        - name: LOGIN_SCOPES
          value: 'openid profile 0dc85ed5-a4d7-4893-8424-700ee6725067/.default'
        - name: OIDC_AUTH_PROXY_BASE_URL
          value: https://k9-los-oidc-auth-proxy.nais.adeo.no
        - name: APPLICATION_BASE_URL
          value: https://k9-los-web.nais.adeo.no
        - name: ALLOW_PROXY_TO_SELF_SIGNED_CERTIFICATES
          value: 'true'
        - name: SESSION_ID_COOKIE_NAME
          value: k9-los-web
        - name: PROXY_CONFIG
          value: '{"apis":[{"path":"k9-los-api","url":"https://k9-los-api.nais.adeo.no/api","scopes":"37066d6c-842c-470a-85f1-3149a37da2c2/.default","webSocketUrl":"ws://k9-los-api.default.svc.nais.local/ws"}]}'
        - name: REDIS_HOST
          value: k9-los-oidc-auth-proxy-redis.default.svc.nais.local
        - name: REDIS_PORT
          value: '6379'
        - name: CORS_ALLOWED_HEADERS
          value: 'Content-Type,Referer,X-Nav-NorskIdent,cache-control,expires,nav-callid,pragma'
        - name: CORS_EXPOSED_HEADERS
          value: 'Location'

