name: Deploy OIDC auth proxy
on:
  push:
    paths:
      - 'deploy/k9-los-oidc-auth-proxy.yml'
    branches:
      - master
jobs:
  deploy-dev:
    name: Deploye til DEV
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v1
      - name: Deploye til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
        with:
          cluster: dev-fss
          team: k9saksbehandling
          rawresources: nais/dev/k9-los-oidc-auth-proxy.yml
