name: Deploy til preprod

on: [workflow_dispatch]

env:
  BASE_IMAGE: ghcr.io/${{ github.repository }}
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy-dev:
    name: Deploye til DEV
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2.3.4
      - name: Sette opp Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Installere moduler
        run: npm install
      - name: Sjekke opp mot Lint-regler
        run: npm run lint
      - name: Kjøre tester
        run: npm run test
      - name: Bygge kode
        run: npm run build
      - name: Sette Docker-navn og -tag
        run: |
          echo BASE_IMAGE > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
          echo "IMAGE=${IMAGE}$(cat .docker_image):$(cat .docker_tag)" >> $GITHUB_ENV
      - name: Bygge Docker image
        run: docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
      - name: Laste opp Docker image
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push $(cat .docker_image):$(cat .docker_tag)
          docker tag $(cat .docker_image):$(cat .docker_tag) $(cat .docker_image):latest
          docker push $(cat .docker_image):latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploye til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/dev-fss.yml
